### ISSUE TITLE
Why do I prompt this

### ISSUE THREAD

**Issue by b1gdog** [crisprss/RasmanPotato#1]
![Snipaste_2023-02-15_10-19-51](https://user-images.githubusercontent.com/81157360/218910775-ae203c48-9575-4a0d-969a-cc7df20cfd6a.jpg)

Run x64 application on win7 x64 and prompt "Operation failed or timed out."

![微信图片_20230215101845](https://user-images.githubusercontent.com/81157360/218910637-99950cac-6981-45ee-ae2f-99b6072a6a0c.png)

**Comment by z1ma-0x41-a** [comment]
I have the same problem with Windows Server 2012r2, RPC error code 1717 is meaning "Interface is unknown", apparently, on Server 2012r2 ( and Windows 7 ) used interface is not exist ( or have another UUID ).

I also have tested on Windows 10 21H1 and Windows 2019 Datacenter ( no patches ) without any RPC errors and no connection on pipe was received but in RPCMon I can see what request was sent

**Comment by crisprss** [comment]
> ![Snipaste_2023-02-15_10-19-51](https://user-images.githubusercontent.com/81157360/218910775-ae203c48-9575-4a0d-969a-cc7df20cfd6a.jpg)
> 
> Run x64 application on win7 x64 and prompt "Operation failed or timed out."
> 
> ![微信图片_20230215101845](https://user-images.githubusercontent.com/81157360/218910637-99950cac-6981-45ee-ae2f-99b6072a6a0c.png)

Win7 does indeed not have this interface, I tested it before

**Comment by crisprss** [comment]
> 

May I see some more details in photo? If it send pjpe requests which we can control by SYSTEM, it's no point to fail, maybe you can change endpoint name to RasmanLrpc except VpnikeRpc

**Comment by crisprss** [comment]
> I have the same problem with Windows Server 2012r2, RPC error code 1717 is meaning "Interface is unknown", apparently, on Server 2012r2 ( and Windows 7 ) used interface is not exist ( or have another UUID ).
> 
> I also have tested on Windows 10 21H1 and Windows 2019 Datacenter ( no patches ) without any RPC errors and no connection on pipe was received but in RPCMon I can see what request was sent

May I see some more details in photo? If it sends pipe requests which we can control by SYSTEM, it's no point to fail, maybe you can change endpoint name to RasmanLrpc except VpnikeRpc

**Comment by z1ma-0x41-a** [comment]
> > I have the same problem with Windows Server 2012r2, RPC error code 1717 is meaning "Interface is unknown", apparently, on Server 2012r2 ( and Windows 7 ) used interface is not exist ( or have another UUID ).
> > I also have tested on Windows 10 21H1 and Windows 2019 Datacenter ( no patches ) without any RPC errors and no connection on pipe was received but in RPCMon I can see what request was sent
> 
> May I see some more details in photo? If it sends pipe requests which we can control by SYSTEM, it's no point to fail, maybe you can change endpoint name to RasmanLrpc except VpnikeRpc

sorry, Im a little late

screenshots with debug output:
![serv19_17763_datacenter](https://user-images.githubusercontent.com/82978501/219630827-38611c21-5252-4c4d-98f8-d7cabc3878b6.PNG)
![win10_10240_pro](https://user-images.githubusercontent.com/82978501/219630834-3d01b0cd-bf12-466f-a841-93b52c753475.PNG)
![win10_19044_home](https://user-images.githubusercontent.com/82978501/219630838-60e27130-8517-4065-be7f-17ddfd7fa3da.PNG)
![win10_19044_pro](https://user-images.githubusercontent.com/82978501/219630843-ee2f233f-391d-482e-81ce-f2eff0959bc5.PNG)

Changing endpoint name haven't helped

**Comment by z1ma-0x41-a** [comment]
Could you say with what os version/build etc you tested it?

**Comment by crisprss** [comment]
win10 10.0.17763 N/A Build 17763
Microsoft Windows Server 2019 Datacenter 10.0.17763 N/A Build 17763

**Comment by crisprss** [comment]
> Could you say with what os version/build etc you tested it?

win10 10.0.17763 N/A Build 17763
Microsoft Windows Server 2019 Datacenter 10.0.17763 N/A Build 17763
